2020-04-15 11:32:52,295 ERROR: Exception on /work/20530347 [GET] [in c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\routes.py", line 304, in work
    return render_template('view_course_student.html', course=course, tasks=tasks, student = student, form=form)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\templates\view_course_student.html", line 60, in template
    {% if task.max_scoreand not task.is_done %}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'not'
2020-04-15 11:34:31,890 INFO: Corona LMS startup [in C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\__init__.py:38]
2020-04-15 20:31:50,373 INFO: Corona LMS startup [in C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\__init__.py:38]
2020-04-15 20:33:58,994 INFO: Corona LMS startup [in C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\__init__.py:38]
2020-04-15 20:35:04,397 INFO: Corona LMS startup [in C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\__init__.py:38]
2020-04-15 20:37:27,558 INFO: Corona LMS startup [in C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\__init__.py:38]
2020-04-15 20:40:15,939 INFO: Corona LMS startup [in C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\__init__.py:38]
2020-04-15 20:42:03,039 INFO: Corona LMS startup [in C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\__init__.py:38]
2020-04-15 20:58:19,654 INFO: Corona LMS startup [in C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\__init__.py:38]
2020-04-15 20:58:28,861 ERROR: Exception on /task/20530347/1 [GET] [in c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\routes.py", line 335, in task
    return render_template('view_task_student.html', task=task, student = student, submissions=submissions, form=form)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\vogel\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\vogel\OneDrive\Desktop\CoronaLMS\app\templates\view_task_student.html", line 108, in template
    <p>{{feedback.text}</p>
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
